# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    replaces = [('events', '0002_auto_20171224_1928'), ('events', '0003_auto_20171225_1146'), ('events', '0004_auto_20171225_1322')]

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='front_cropping',
            field=image_cropping.fields.ImageRatioField('front_picture', '250x250', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Beskjæring'),
        ),
        migrations.AddField(
            model_name='event',
            name='front_picture',
            field=models.ImageField(blank=True, help_text='Bilder som er større enn 250x250 px og er kvadratiske ser best ut. Du kan beskjære bildet etter opplasting.', null=True, upload_to='uploads/front_page_pictures', verbose_name='Forsidebilde'),
        ),
    ]
