# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171226_2210_squashed_0003_auto_20171226_2215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set([]),
        ),
    ]
