# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171224_1928_squashed_0004_auto_20171225_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set([]),
        ),
    ]
