# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171225_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '1000x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Beskjæring'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, help_text='Bilder som er større enn 1000x400 px ser best ut. Du kan beskjære bildet etter opplasting.', null=True, upload_to='uploads/news_pictures', verbose_name='Arrangementbilde'),
        ),
    ]
