# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2023-01-17 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20171228_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=80, verbose_name='E-post'),
        ),
    ]
