name: Python testing

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        python_version: ["3.9.16"]
    defaults:
      run:
        shell: bash  # For `source` on all os-es
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m ensurepip --upgrade
        python -m venv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python -Wa manage.py test
